apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-crypto
  labels:
    app: node-crypto
    project: crypto
    tags.datadoghq.com/service: "node-crypto"
    tags.datadoghq.com/version: "1.0"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-crypto
  template:
    metadata:
      annotations:
        ad.datadoghq.com/node-crypto.logs: '[{"source":"node-crypto","service":"node-crypto"}]'
      labels:
        app: node-crypto
        tags.datadoghq.com/service: "node-crypto"
        tags.datadoghq.com/version: "1.0"

    spec:
      containers:
      - name: node-crypto
        image: localhost:32000/node-crypto:latest
        ports:
            - containerPort: 8888
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP

          - name: REDIS_PORT
            value: '30010'

          - name: HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP

          - name: DD_TAGS
            value: "service:node-crypto"

          - name: CURRENCY
            value: "EUR"

          - name: COINS
            value: "BTC,ETH,LTC,XRP,XLM,DOGE,XTZ,BCH,EOS,OMG,ZRX"

          - name: METRIC_SUBMISSION_INTERVAL
            value: '10'

          - name: VALUE_COLLECTION_INTERVAL
            value: '60'

          - name: STATS_INTERVAL
            value: '43200'


---
apiVersion: v1
kind: Service
metadata:
  name: node-crypto
spec:
  selector:
    app: node-crypto
  ports:
    - name: http
      protocol: TCP
      port: 8888
      nodePort: 30011
  type: LoadBalancer
